name: Build RTOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ARM GCC Toolchain
      run:  |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi

    - name: Build project
      run: |
        cd Debug
        make all

    - name: Upload Build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rtos-firmware
        path: | 
          Debug/RTOS.elf
          Debug/RTOS.hex